# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: blockchain.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'blockchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62lockchain.proto\x12\nblockchain\"d\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x15\n\rprevious_hash\x18\x03 \x01(\t\x12\x0c\n\x04hash\x18\x04 \x01(\t\x12\x14\n\x0ctransactions\x18\x05 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"*\n\x05\x43hain\x12!\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x11.blockchain.Block2\xec\x01\n\x11\x42lockchainService\x12\x39\n\x0e\x42roadcastBlock\x12\x11.blockchain.Block\x1a\x14.blockchain.Response\x12\x34\n\x0cRequestChain\x12\x11.blockchain.Empty\x1a\x11.blockchain.Chain\x12/\n\x04Ping\x12\x11.blockchain.Empty\x1a\x14.blockchain.Response\x12\x35\n\nResetChain\x12\x11.blockchain.Empty\x1a\x14.blockchain.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'blockchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCK']._serialized_start=32
  _globals['_BLOCK']._serialized_end=132
  _globals['_RESPONSE']._serialized_start=134
  _globals['_RESPONSE']._serialized_end=160
  _globals['_EMPTY']._serialized_start=162
  _globals['_EMPTY']._serialized_end=169
  _globals['_CHAIN']._serialized_start=171
  _globals['_CHAIN']._serialized_end=213
  _globals['_BLOCKCHAINSERVICE']._serialized_start=216
  _globals['_BLOCKCHAINSERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
