# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import blockchain_pb2 as blockchain__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in blockchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BlockchainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastBlock = channel.unary_unary(
                '/blockchain.BlockchainService/BroadcastBlock',
                request_serializer=blockchain__pb2.Block.SerializeToString,
                response_deserializer=blockchain__pb2.Response.FromString,
                _registered_method=True)
        self.RequestChain = channel.unary_unary(
                '/blockchain.BlockchainService/RequestChain',
                request_serializer=blockchain__pb2.Empty.SerializeToString,
                response_deserializer=blockchain__pb2.Chain.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/blockchain.BlockchainService/Ping',
                request_serializer=blockchain__pb2.Empty.SerializeToString,
                response_deserializer=blockchain__pb2.Response.FromString,
                _registered_method=True)
        self.ResetChain = channel.unary_unary(
                '/blockchain.BlockchainService/ResetChain',
                request_serializer=blockchain__pb2.Empty.SerializeToString,
                response_deserializer=blockchain__pb2.Response.FromString,
                _registered_method=True)


class BlockchainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BroadcastBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlockchainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastBlock,
                    request_deserializer=blockchain__pb2.Block.FromString,
                    response_serializer=blockchain__pb2.Response.SerializeToString,
            ),
            'RequestChain': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChain,
                    request_deserializer=blockchain__pb2.Empty.FromString,
                    response_serializer=blockchain__pb2.Chain.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=blockchain__pb2.Empty.FromString,
                    response_serializer=blockchain__pb2.Response.SerializeToString,
            ),
            'ResetChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetChain,
                    request_deserializer=blockchain__pb2.Empty.FromString,
                    response_serializer=blockchain__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blockchain.BlockchainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blockchain.BlockchainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BlockchainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BroadcastBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainService/BroadcastBlock',
            blockchain__pb2.Block.SerializeToString,
            blockchain__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainService/RequestChain',
            blockchain__pb2.Empty.SerializeToString,
            blockchain__pb2.Chain.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainService/Ping',
            blockchain__pb2.Empty.SerializeToString,
            blockchain__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blockchain.BlockchainService/ResetChain',
            blockchain__pb2.Empty.SerializeToString,
            blockchain__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
